### ISSUE TITLE
fetche

### ISSUE THREAD

**Issue by xiaoqixiaoqi1113** [erictik/midjourney-client#128]
### the code that reproduces this issue or a replay of the bug

const { Midjourney } = require("midjourney")
const axios = require('axios')
const express = require('express')
const router = express.Router();

const client = new Midjourney({
    ServerId: process.env.SERVER_ID,
    ChannelId: process.env.CHANNEL_ID,
    SalaiToken: process.env.SALAI_TOKEN,
    Debug: true,
    Ws: true,
});

client.init()

router.post("/image", async ({ body: { prompt } }, rej) => {

    console.log(prompt);

    const Imagine = await client.Imagine(prompt);

    const imgName = Imagine.uri.split("/").at(-1)

    const { data } = await axios.get(Imagine.uri, { responseType: 'arraybuffer' })

    rej.send({ Imagine: Imagine.uri, imgName })
})

module.exports = router

### Describe the bug

 I haven't touched any code. Yesterday, I tried it and it was working, but today it's giving me an error.

### error log

0|server   | ReferenceError: fetch is not defined
0|server   |     at MidjourneyApi.interactions (/home/noServer/node_modules/midjourney/libs/midjourne.api.js:37:30)
0|server   |     at /home/noServer/node_modules/midjourney/libs/midjourne.api.js:22:18
0|server   |     at new Promise (<anonymous>)
0|server   |     at /home/noServer/node_modules/midjourney/libs/midjourne.api.js:21:44
0|server   |     at /home/noServer/node_modules/midjourney/libs/queue.js:17:34
0|server   |     at run (/home/noServer/node_modules/p-queue/dist/index.js:157:104)
0|server   |     at PQueue._tryToStartAnother (/home/noServer/node_modules/p-queue/dist/index.js:105:17)
0|server   |     at /home/noServer/node_modules/p-queue/dist/index.js:171:18
0|server   |     at new Promise (<anonymous>)
0|server   |     at PQueue.add (/home/noServer/node_modules/p-queue/dist/index.js:152:16)
0|server   | Error: ImagineApi failed with status 500
0|server   |     at Midjourney.Imagine (/home/noServer/node_modules/midjourney/libs/midjourney.js:49:19)
0|server   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|server   |     at async /home/noServer/routers/midjourneyApi.js:20:21

**Comment by zcpua** [comment]
node > 18

**Comment by zcpua** [comment]
import fetch from 'node-fetch'
import { Midjourney } from 'midjourney'
import { SocksProxyAgent } from 'socks-proxy-agent';

// 也可以是：https-proxy-agent 或 https-proxy-agent
const agent = new SocksProxyAgent('socks5://127.0.0.1:10886', { keepAlive: true });

// 全局替换 midjourney 内部的 fetch 的方法
global.fetch = function fetchProxy(input, init = {}) {
  // 添加代理
  init.agent = agent;

  return fetch(input, init)
}

const api = new Midjourney({
  ServerId: process.env.SERVER_ID,
  ChannelId: process.env.CHANNEL_ID,
  SalaiToken: process.env.SALAI_TOKEN,
  Debug: true,
})

// 获取图片
console.log(await api.Imagine('cat'))

**Comment by xiaoqixiaoqi1113** [comment]
全局替换的话我要怎么做呢，我之前没这样写过

**Comment by zcpua** [comment]
last version
```
import fetch from 'node-fetch'
import { Midjourney } from 'midjourney'

const api = new Midjourney({
  ServerId: process.env.SERVER_ID,
  ChannelId: process.env.CHANNEL_ID,
  SalaiToken: process.env.SALAI_TOKEN,
  Debug: true,
  fetch:fetch,
})
```

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-discord/blob/main/examples/proxy.ts

**Comment by zcpua** [comment]
midjourney version

**Comment by iamkunal9** [comment]
> ```
> /home/hortinstein/gyogyo/node_modules/midjourney/libs/midjourne.api.js:7
> const node_fetch_1 = tslib_1.__importDefault(require("node-fetch"));
>                                              ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/hortinstein/gyogyo/node_modules/node-fetch/src/index.js from /home/hortinstein/gyogyo/node_modules/midjourney/libs/midjourne.api.js not supported.
> Instead change the require of index.js in /home/hortinstein/gyogyo/node_modules/midjourney/libs/midjourne.api.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/home/hortinstein/gyogyo/node_modules/midjourney/libs/midjourne.api.js:7:46)
>     at Object.<anonymous> (/home/hortinstein/gyogyo/node_modules/midjourney/libs/midjourney.js:5:25)
>     at Object.<anonymous> (/home/hortinstein/gyogyo/node_modules/midjourney/libs/index.js:4:22) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v20.3.0
> ```
> 
> Any idea how to get around this?

use old version of node-fetch its a common error try using v2.6.11

**Comment by hortinstein** [comment]
Thanks got it working by incrementing the version for this repo

**Comment by yohandarosa** [comment]
I'm still stuck with this error and I've tried your solutions

```
Detailed stack trace: ReferenceError: fetch is not defined
    at Object.<anonymous> (/workspace/node_modules/midjourney/libs/interfaces/config.js:16:12)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/workspace/node_modules/midjourney/libs/interfaces/index.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)`
```
Here are my different versions

```
├── @google-cloud/pubsub@3.7.1
├── axios@1.4.0
├── eslint-config-google@0.14.0
├── eslint@8.43.0
├── firebase-admin@10.3.0
├── firebase-functions-test@0.2.3
├── firebase-functions@4.4.1
├── luxon@3.3.0
├── midjourney@3.1.88
└── node-fetch@2.6.11
```

thank you all

**Comment by iamkunal9** [comment]
> I'm still stuck with this error and I've tried your solutions
> 
> ```
> Detailed stack trace: ReferenceError: fetch is not defined
>     at Object.<anonymous> (/workspace/node_modules/midjourney/libs/interfaces/config.js:16:12)
>     at Module._compile (node:internal/modules/cjs/loader:1196:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
>     at Module.load (node:internal/modules/cjs/loader:1074:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
>     at Module.require (node:internal/modules/cjs/loader:1098:19)
>     at require (node:internal/modules/cjs/helpers:108:18)
>     at Object.<anonymous> (/workspace/node_modules/midjourney/libs/interfaces/index.js:5:22)
>     at Module._compile (node:internal/modules/cjs/loader:1196:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)`
> ```
> 
> Here are my different versions
> 
> ```
> ├── @google-cloud/pubsub@3.7.1
> ├── axios@1.4.0
> ├── eslint-config-google@0.14.0
> ├── eslint@8.43.0
> ├── firebase-admin@10.3.0
> ├── firebase-functions-test@0.2.3
> ├── firebase-functions@4.4.1
> ├── luxon@3.3.0
> ├── midjourney@3.1.88
> └── node-fetch@2.6.11
> ```
> 
> thank you all

Have u tried with the older version of midjourney try with ("midjourney": "^2.7.79") and i dont think you have to install the fetch by yourself just try creating a code follow the steps:-
`mkdir new
cd new
touch index.js
npm init
npm i midjourney
`
And just try by placing the boiler plate code given!!
