### ISSUE TITLE
latest issue...

### ISSUE THREAD

**Issue by lordmen99** [erictik/midjourney-client#21]
latest version, send error like this :

Error: ImagineApi failed with status 401
    at Midjourney.<anonymous> (/main/server/node_modules/midjourney/libs/midjourney.js:26:23)

**Comment by CAPTAIN320** [comment]
Having the same issue

**Comment by iamkunal9** [comment]
> Having the same issue but getting status 400 instead

setup serverid and channel id correctly

**Comment by CAPTAIN320** [comment]
> > Having the same issue but getting status 400 instead
> 
> setup serverid and channel id correctly

Works, Thanks

**Comment by jubak01** [comment]
Anyone had been able to solve it ?

**Comment by jubak01** [comment]
> latest version, send error like this :
> 
> Error: ImagineApi failed with status 401 at Midjourney. (/main/server/node_modules/midjourney/libs/midjourney.js:26:23)

Check if you have the last version of the MidJourney module, last version is 2.3.42
